# Generated by Django 5.1.7 on 2025-03-12 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_avaiable',
            new_name='is_available',
        ),
    ]
